apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ecr-cred-helper.fullname" . }}
  labels:
  {{- include "ecr-cred-helper.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
  {{- include "ecr-cred-helper.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
    {{- include "ecr-cred-helper.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ecr-cred-helper.serviceAccountName" . }}
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: AWS_ACCESS_KEY_ID
                  name: {{ include "ecr-cred-helper.secretName" . }}
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: AWS_SECRET_ACCESS_KEY
                  name: {{ include "ecr-cred-helper.secretName" . }}
            - name: AWS_DEFAULT_REGION
              value: {{ .Values.aws.region }}
            - name: DOCKER_REGISTRY
              value: {{ include "ecr-cred-helper.registryHostname" . }}
            - name: ECR_SECRET_NAME
              value: {{ .Values.aws.generatedSecretName }}
            - name: ECR_LABEL_NAME
              value: {{ .Values.aws.labelName }}
            - name: ECR_LABEL_VALUE
              value: {{ .Values.aws.labelValue }}
            - name: ECR_CRON_SCHEDULE
              value: {{ .Values.aws.cronSchedule }}
          resources:
      {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
  {{- end }}
