{{- if .Values.aws.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ecr-cred-helper.secretName" . }}
  labels:
  {{- include "ecr-cred-helper.labels" . | nindent 4 }}
  {{- with .Values.aws.secretAnnotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ include "ecr-cred-helper.accessKeyId" . }}
  AWS_SECRET_ACCESS_KEY: {{ include "ecr-cred-helper.secretAccessKey" . }}
  {{- end }}
